##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 12 16:19:53 CET 2000
#    copyright            : (C) 2000, 2012 by Eric Espie, Bernhard Wymann                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.1.2.1 2012/10/18 13:20:52 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

DATADIR   = tracks/dirt/dirt-2

DATA      = dirt-2.xml background.png dirt-2.acc dirt-2.png readme.txt \
	    barrier-d2.png BLBDBK.png concretetile.png CONCSH01.png curb-bw-d2.png \
	    dirt-bw-d2.png dirt-bw-lines-left-d2.png dirt-side-bw-d2.png \
	    dirt-side-pit-bw-d2.png grass-bw-d2.png house12.png house12r.png \
	    house13.png house13r.png house14r.png house15.png logo_trb2.png \
	    logo_water.png megafuel_trucktank.png mycast.png PASS10.png PASS3.png \
	    PASS4.png pitfacade1.png pitfacade2.png pylon1.rgb pylon2.rgb pylon3.rgb \
	    raceline-bw-d2.png readme.txt red_bridge.png roof11.png shadow2.rgb \
	    silo1-pipe.png silo1-w.png strawbale-bw.png trb_red_bridge.png \
	    tree10_n.png tree13_n.png tree15_n.png tree18_n.png treeS3_n.png \
	    treeUGLIES02_n.png truck_arbor_bt_n.png truck_arbor_speedy_n.png \
	    wall11.png wall14-2.png wall14.png wall-concrete.png wall-water.png

data-tracks-dirt_PKGFILES	= $(DATA)

data-tracks-dirt_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


