##############################################################################
#
#    file        : Makefile<3>
#    created     : Sun Apr 20 23:03:13 CEST 2003
#    copyright   : (C) 2003 by Eric Espié                        
#    email       : Eric.Espie@torcs.org   
#    version     : $Id: Makefile,v 1.4.2.1 2012/09/08 01:53:53 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################



DATADIR   = tracks/road/spring

DATA      = spring.xml spring.acc spring.png readme.txt raceline.png background.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)



include ${MAKE_DEFAULT}


