##############################################################################
#
#    file                 : Makefile
#    created              : Tue Sep 25 02:21:46 CET 2012
#    copyright            : (C) 2012 by Bernhard Wymann                         
#    email                : berniw@bluewin.ch   
#    version              : $Id: Makefile,v 1.1.2.2 2012/09/25 09:05:13 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/e-track-3

DATA      = e-track-3.xml background.png e-track-3.acc e-track-3.png readme.txt \
	    asphalt2-bw-e3.png asphalt-bw-e3-lines-l.png asphalt-bw-e3-pit-l.png asphalt-bw-e3.png \
	    asphalt-white-tile.png back-sign.png barrier.png BLBDBK.png concrete2.rgb concrete.rgb \
	    CONCSH01.png curb-green-carpet.png curb-red-carpet.png curb-white-concrete.png \
	    fence_arbor_n.png grass-e3.png grass-side-e3.png logo_megafuel.png \
	    logo_trb2.png logo_x4y.png megafuel-wall.png mycast.png PASS10.png PASS3.png PASS4.png \
	    PDKKA13.png pylon1.rgb pylon2.rgb pylon3.rgb raceline.png readme.txt shadow2.rgb \
	    tirewall.png tree11_n.png tree12_n.png tree195_n.png tree19_n.png tree35_n.png \
	    tree4_n.png treeS3_n.png treeUGLIES01_n.png TRIBA08.png TRIBA11.png TRIBB01.png \
	    TRIBB02.png TRIBB03.png turn100.png turn200.png turn25.png turn300.png turn50.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)


include ${MAKE_DEFAULT}


