##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999, 2012 by Eric Espie; Bernhard Wymann                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.1.2.1 2012/10/08 08:19:43 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/wheel-1

DATA      = wheel-1.xml background.png wheel-1.acc wheel-1.png readme.txt asphalt2-bw-w1.png asphalt-border-bw-w1.png \
	    asphalt-bw-w1-lines-l.png asphalt-bw-w1-pit-l.png asphalt-bw-w1.png asphalt-white-tile.png \
	    back-sign.png barrier-metal-bw-w1.png BLBDBK.png block4f.png block4s.png concrete2.rgb concrete.rgb \
	    CONCSH01.png curb-yellow-blue.png curb-yellow-red.png fence_arbor_n.png flatspot-wall.png \
	    garage1.png garage2.png garage3.png garage5.png grass-border-bw-w1.png grass-bw-w1.png \
	    grass-grey-bw-w1.png house10f.png house10r.png logo_cmyk.png logo_flatspot.png logo_trb2.png \
	    mycast.png PASS10.png PASS3.png PASS4.png PDKKA13.png pylon1.rgb pylon2.rgb pylon3.rgb raceline.png \
	    rock1-w1.png sand-border-bw-w1.png sand-bw-w1.png shadow2.rgb shadow3.png tirewall.png tree2_n.png \
	    tree5_n.png tree6_n.png tree7_n.png tree8_n.png treeS3_n.png treeUGLIES01_n.png TRIBA08.png \
	    TRIBA11.png TRIBB01.png TRIBB02.png TRIBB03.png truck_arbor_bt_n.png truck_arbor_cylos_n.png \
	    turn100.png turn200.png turn25.png turn50.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


